### ISSUE TITLE
update rollup configuration

### ISSUE THREAD

**Issue by achmadk** [bondz/react-epic-spinners#24]
Hello, @bondz , this library helps me to use epic-spinner in react with ease.

Can I help you to update rollup configuration of your library? Recently, rollup has been upgraded to version 2. Several rollup plugin has been renamed from `rollup-plugin-*` to `@rollup/plugin-`. Maybe you can check updated rollup configuration and other configuration [here](https://github.com/bondz/react-epic-spinners/compare/master...achmadk:update-dependencies-into-latest-version?expand=1#diff-ff6e5f22a9c7e66987b19c0199636480) .

I'am very happy if you accept my request.

**Comment by bondz** [comment]
Hello @achmadk :)

I was very surprised to see this. I had done just this a few weeks back but forgot to push my changes to GitHub lol. I've gone through your changes and it's exactly what I'd done.

Yes, please, go ahead and create the pull request. I'm very happy to accept it :)

**Comment by achmadk** [comment]
I have created PR for this issue. If you don't mind, can you add label `hacktoberfest-accepted` for [that](https://github.com/bondz/react-epic-spinners/pull/25) PR?

**Comment by bondz** [comment]
@achmadk done 👍
