### ISSUE TITLE
react should be a peerDependency, not a dependency

### ISSUE THREAD

**Issue by CharlesW95** [bondz/react-epic-spinners#26]
Hi @bondz ! Amazing work on this package, I've enjoyed using it so far.

I was wondering - shouldn't react be listed under `peerDependencies` and not under `dependencies` in `package.json`? I'm getting a `multiple versions of react` error when I try installing/running this with hooks - because the package itself is installing its own version of react. I expect any project using this package will have react already installed as an explicit dependency - and so it would be safer to express react as a peerDependency in this case. I think most other pure UI component packages do this as well.

Curious to get your thoughts on this!

**Comment by bondz** [comment]
@CharlesW95 thanks for the kind words.

With the current dependency version, the package manager should use any version of react >= 0.14.x, which should be compatible with any version of react greater than that version.

Using `yarn` to install the library in a new project resolved the version of react to

```
react@>=0.14.x, react@^17.0.1:
  version "17.0.1"
  resolved "https://registry.yarnpkg.com/react/-/react-17.0.1.tgz#6e0600416bd57574e3f86d92edba3d9008726127"
  integrity sha512-lG9c9UuMHdcAexXtigOZLX8exLWkW0Ku29qPRU8uhF2R9BN96dLCt0psvzPLlHc5OWkgymP3qwTRgbnw5BKx3w==
  dependencies:
    loose-envify "^1.1.0"
    object-assign "^4.1.1"
```

Using npm also has

```json
    "react": {
      "version": "17.0.1",
      "resolved": "https://registry.npmjs.org/react/-/react-17.0.1.tgz",
      "integrity": "sha512-lG9c9UuMHdcAexXtigOZLX8exLWkW0Ku29qPRU8uhF2R9BN96dLCt0psvzPLlHc5OWkgymP3qwTRgbnw5BKx3w==",
      "requires": {
        "loose-envify": "^1.1.0",
        "object-assign": "^4.1.1"
      }
    },
```

I'm not opposed to making it a peerDependency though. I just want to your scenario and why your package manager installed multiple versions.

**Comment by CharlesW95** [comment]
Hey @bondz, thanks for getting back to me! I apologize - I think I misspoke - I meant multiple **copies** of react, not versions. In my case `react-epic-spinners` is installing its own copy of react, and so is my project. When they both get loaded at runtime, that is causing issues I believe with singletons that are being generated in each of the copies of react - even though they are both the same version, namely `17.0.1`, and that's where the hooks issues is coming from.

With a peerDependency, we'd be able to ensure there's always one copy of react across the entire project, and can avoid these issues - does that help?

**Comment by bondz** [comment]
@CharlesW95 :) That's great. I'm open to switching to peerDependencies.

**Comment by CharlesW95** [comment]
Great! I can PR if you want?

**Comment by bondz** [comment]
@CharlesW95 definitely. Thank you.
